// ── PDF Report Generator ─────────────────────────────────────────────
// Uses jsPDF + autoTable plugin

async function generatePDFReport(token) {

    const { jsPDF } = window.jspdf;
    const doc        = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

    const W = doc.internal.pageSize.getWidth();
    const H = doc.internal.pageSize.getHeight();

    // Fetch all data
    const [analytics, trades, journals, monthly] = await Promise.all([
        getAnalytics(token),
        getTrades(token),
        getJournals(token),
        getMonthlyPerformance(token)
    ]);

    const email   = (() => {
        try { return JSON.parse(atob(token.split(".")[1])).email; }
        catch { return "Voyager User"; }
    })();

    const now       = new Date();
    const reportDate = now.toLocaleDateString("en-GB", { day:"2-digit", month:"long", year:"numeric" });


    // ── PAGE 1: COVER ────────────────────────────────────────────────

    // Dark background
    doc.setFillColor(7, 11, 20);
    doc.rect(0, 0, W, H, "F");

    // Accent bar
    doc.setFillColor(0, 212, 255);
    doc.rect(0, 0, W, 3, "F");

    // Logo text
    doc.setFont("helvetica", "bold");
    doc.setFontSize(28);
    doc.setTextColor(255, 255, 255);
    doc.text("VOYAGER", W / 2, 60, { align: "center" });

    doc.setFontSize(11);
    doc.setTextColor(0, 212, 255);
    doc.setFont("helvetica", "normal");
    doc.text("ANALYTICS", W / 2, 70, { align: "center" });

    // Divider
    doc.setDrawColor(0, 212, 255);
    doc.setLineWidth(0.3);
    doc.line(40, 80, W - 40, 80);

    // Report title
    doc.setFontSize(18);
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.text("Performance Report", W / 2, 100, { align: "center" });

    // Trader info
    doc.setFontSize(11);
    doc.setTextColor(148, 163, 184);
    doc.setFont("helvetica", "normal");
    doc.text(email, W / 2, 115, { align: "center" });
    doc.text(reportDate, W / 2, 123, { align: "center" });

    // KPI boxes on cover
    const kpis = [
        { label: "Total Profit",  value: `$${analytics.total_profit}` },
        { label: "Win Rate",      value: `${analytics.win_rate}%`     },
        { label: "Total Trades",  value: analytics.trade_count        },
        { label: "Profit Factor", value: analytics.profit_factor      }
    ];

    const boxW  = (W - 50) / 2;
    const boxH  = 24;
    const startX = 20;
    let   startY = 145;

    kpis.forEach((kpi, i) => {
        const x = startX + (i % 2) * (boxW + 10);
        const y = startY + Math.floor(i / 2) * (boxH + 8);

        doc.setFillColor(16, 24, 39);
        doc.roundedRect(x, y, boxW, boxH, 3, 3, "F");

        doc.setFontSize(9);
        doc.setTextColor(148, 163, 184);
        doc.text(kpi.label, x + 8, y + 9);

        doc.setFontSize(14);
        doc.setTextColor(0, 212, 255);
        doc.setFont("helvetica", "bold");
        doc.text(String(kpi.value), x + 8, y + 19);
        doc.setFont("helvetica", "normal");
    });

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by Voyager Analytics", W / 2, H - 15, { align: "center" });


    // ── PAGE 2: PERFORMANCE SUMMARY ──────────────────────────────────

    doc.addPage();
    doc.setFillColor(7, 11, 20);
    doc.rect(0, 0, W, H, "F");
    doc.setFillColor(0, 212, 255);
    doc.rect(0, 0, W, 3, "F");

    // Header
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text("Performance Summary", 20, 25);

    doc.setDrawColor(30, 41, 59);
    doc.setLineWidth(0.3);
    doc.line(20, 30, W - 20, 30);

    // Stats table
    const stats = [
        ["Total Profit",    `$${analytics.total_profit}`,    "Net P&L across all trades"],
        ["Win Rate",        `${analytics.win_rate}%`,         "Percentage of winning trades"],
        ["Total Trades",    analytics.trade_count,            "Number of closed trades"],
        ["Profit Factor",   analytics.profit_factor,          "Gross profit / gross loss"],
        ["Expectancy",      `$${analytics.expectancy}`,       "Average expected return per trade"],
        ["Average Win",     `$${analytics.average_win}`,      "Average profit on winning trades"],
        ["Average Loss",    `$${analytics.average_loss}`,     "Average loss on losing trades"],
        ["Largest Win",     `$${analytics.largest_win}`,      "Best single trade"],
        ["Largest Loss",    `$${analytics.largest_loss}`,     "Worst single trade"],
        ["Max Drawdown",    `$${analytics.max_drawdown}`,     "Largest peak-to-trough decline"],
        ["Average Trade",   `$${analytics.average_trade}`,   "Average P&L per trade"],
    ];

    doc.autoTable({
        startY: 38,
        head: [["Metric", "Value", "Description"]],
        body: stats,
        theme: "plain",
        headStyles: {
            fillColor:  [16, 24, 39],
            textColor:  [0, 212, 255],
            fontStyle:  "bold",
            fontSize:   9
        },
        bodyStyles: {
            fillColor:  [7, 11, 20],
            textColor:  [255, 255, 255],
            fontSize:   9,
            cellPadding: 5
        },
        alternateRowStyles: {
            fillColor: [16, 24, 39]
        },
        columnStyles: {
            0: { cellWidth: 45, fontStyle: "bold" },
            1: { cellWidth: 35, textColor: [0, 212, 255] },
            2: { textColor: [148, 163, 184] }
        },
        margin: { left: 20, right: 20 }
    });


    // ── PAGE 3: MONTHLY BREAKDOWN ─────────────────────────────────────

    doc.addPage();
    doc.setFillColor(7, 11, 20);
    doc.rect(0, 0, W, H, "F");
    doc.setFillColor(0, 212, 255);
    doc.rect(0, 0, W, 3, "F");

    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text("Monthly Breakdown", 20, 25);

    doc.setDrawColor(30, 41, 59);
    doc.line(20, 30, W - 20, 30);

    const monthlyRows = monthly.map(m => [
        m.month,
        `$${m.profit}`,
        m.trades,
        `${m.win_rate}%`,
        m.profit >= 0 ? "Profitable" : "Loss"
    ]);

    doc.autoTable({
        startY: 38,
        head: [["Month", "Profit", "Trades", "Win Rate", "Result"]],
        body: monthlyRows,
        theme: "plain",
        headStyles: {
            fillColor: [16, 24, 39],
            textColor: [0, 212, 255],
            fontStyle: "bold",
            fontSize:  9
        },
        bodyStyles: {
            fillColor: [7, 11, 20],
            textColor: [255, 255, 255],
            fontSize:  9,
            cellPadding: 5
        },
        alternateRowStyles: {
            fillColor: [16, 24, 39]
        },
        columnStyles: {
            1: { textColor: [0, 212, 255] },
            4: { textColor: [148, 163, 184] }
        },
        margin: { left: 20, right: 20 }
    });


    // ── PAGE 4: TOP TRADES ───────────────────────────────────────────

    doc.addPage();
    doc.setFillColor(7, 11, 20);
    doc.rect(0, 0, W, H, "F");
    doc.setFillColor(0, 212, 255);
    doc.rect(0, 0, W, 3, "F");

    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text("Top Trades", 20, 25);
    doc.setDrawColor(30, 41, 59);
    doc.line(20, 30, W - 20, 30);

    // Best 5
    doc.setFontSize(11);
    doc.setTextColor(0, 212, 255);
    doc.text("Best Trades", 20, 42);

    const bestTrades = [...trades]
        .sort((a, b) => b.profit - a.profit)
        .slice(0, 5)
        .map(t => [t.symbol, t.order_type, t.lot_size, `+$${t.profit}`]);

    doc.autoTable({
        startY: 46,
        head: [["Symbol", "Type", "Lot Size", "Profit"]],
        body: bestTrades,
        theme: "plain",
        headStyles: { fillColor: [16, 24, 39], textColor: [0, 212, 255], fontSize: 9 },
        bodyStyles: { fillColor: [7, 11, 20], textColor: [255, 255, 255], fontSize: 9, cellPadding: 5 },
        alternateRowStyles: { fillColor: [16, 24, 39] },
        margin: { left: 20, right: 20 }
    });

    // Worst 5
    const afterBest = doc.lastAutoTable.finalY + 12;
    doc.setFontSize(11);
    doc.setTextColor(239, 68, 68);
    doc.text("Worst Trades", 20, afterBest);

    const worstTrades = [...trades]
        .sort((a, b) => a.profit - b.profit)
        .slice(0, 5)
        .map(t => [t.symbol, t.order_type, t.lot_size, `$${t.profit}`]);

    doc.autoTable({
        startY: afterBest + 4,
        head: [["Symbol", "Type", "Lot Size", "Loss"]],
        body: worstTrades,
        theme: "plain",
        headStyles: { fillColor: [16, 24, 39], textColor: [239, 68, 68], fontSize: 9 },
        bodyStyles: { fillColor: [7, 11, 20], textColor: [255, 255, 255], fontSize: 9, cellPadding: 5 },
        alternateRowStyles: { fillColor: [16, 24, 39] },
        margin: { left: 20, right: 20 }
    });


    // ── PAGE 5: JOURNAL SUMMARY ──────────────────────────────────────

    if(journals.length > 0){
        doc.addPage();
        doc.setFillColor(7, 11, 20);
        doc.rect(0, 0, W, H, "F");
        doc.setFillColor(0, 212, 255);
        doc.rect(0, 0, W, 3, "F");

        doc.setFontSize(16);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(255, 255, 255);
        doc.text("Journal Summary", 20, 25);
        doc.setDrawColor(30, 41, 59);
        doc.line(20, 30, W - 20, 30);

        // Emotion breakdown
        const emotionCount = {};
        journals.forEach(j => {
            if(j.emotion) emotionCount[j.emotion] = (emotionCount[j.emotion] || 0) + 1;
        });

        const avgRating = (
            journals.reduce((sum, j) => sum + (j.rating || 0), 0) / journals.length
        ).toFixed(1);

        const emotionRows = Object.entries(emotionCount).map(([emotion, count]) => [
            emotion,
            count,
            `${Math.round((count / journals.length) * 100)}%`
        ]);

        doc.setFontSize(11);
        doc.setTextColor(0, 212, 255);
        doc.text(`Total Entries: ${journals.length}   Average Rating: ${avgRating}/10`, 20, 42);

        doc.autoTable({
            startY: 48,
            head: [["Emotion", "Count", "Frequency"]],
            body: emotionRows,
            theme: "plain",
            headStyles: { fillColor: [16, 24, 39], textColor: [0, 212, 255], fontSize: 9 },
            bodyStyles: { fillColor: [7, 11, 20], textColor: [255, 255, 255], fontSize: 9, cellPadding: 5 },
            alternateRowStyles: { fillColor: [16, 24, 39] },
            margin: { left: 20, right: 20 }
        });
    }

    // ── SAVE ─────────────────────────────────────────────────────────

    const filename = `voyager-report-${now.toISOString().slice(0, 10)}.pdf`;
    doc.save(filename);
}